<!-- Methods -->

## Field trials and phenotyping
The ASBP runs a clonally replicated field trial for each of the three growing regions each year. The subtropical and temperate trials are hosted at DPI-operated facilities in Nambour in South East Queensland, and Wandin North in Victoria, respectively. The Mediterranean clonal trial is hosted at a grower's property, with some incomplete data; data from the Mediterranean region are thus not included in the current study. 

Plug plants were used each year at Nambour, with ASBP variety 'Red Rhapsody' used as a check each year. Bare-rooted runners, produced from runner propagation in sand beds, were used at Wandin in 2021-22 and 2022-23 seasons, a combination of bare-rooted runners and plugs were used in 2023-24, and plugs were exclusively used in 204-25. Large plant crowns were occasionally broken into pieces to obtain required plant numbers. Across the four trial years, a combination of varieties 'Albion', 'Monterey' and 'Cabrillo' were used as checks.

Trial design.

The subtropical trials are planted in March (southern-hemisphere autumn), fruit begins to ripen in April or May, and harvest continues from first fruit through to the end of August (winter). The temperate trials are planted between April and June, with the first fruits ripening in October. Harvest continued through to the end of February in the 2021-22 season, end of March in 2022-23, and the middle May in both 2023-24 and 2024-25. 

Each week, fruit (>70% ripe) were harvested and pooled within a six-plant plot, counted and weighed, and various quality assessments performed. Weekly yield per plant (yldpp) was calculated as the weekly yield divided by the number of plants per plot. Average fruit weight (avfrtwt) was calculated as the weekly yield divided by the number of fruit. 

## Construction of A-matrices
Pedigree depths of two (i.e. the accessions present in the phenotypic data and their parents) to seven were used. The following methods were used to construct A-matrices: (i) ainverse function in asreml [@asremlr; @asreml], denoted as a.ainv; (ii) the nrm function in pedicure [@pedicure], denoted p.nrm; (iii) the Amatrix function with ploidy = 2 in AGHmatrix [@AGHmatrix], denoted agh.2; and (iv) the Amatrix function with ploidy = 8 in AGHmatrix [@AGHmatrix], denoted agh.8.

An inbreeding founder value of 1e-06 was used, and a tolerance/zap value of 1e-10 was used, as this is the unchangeable default in asreml. 

*If we find that an octoploid A matrix is a better fit than diploid, then we should explore different levels of double reduction (the probability that two sister chromatids pass into the same gamete), as per @Amadeu2016.*

A-matrices were compared between methods within each pedigree depth using a Pearson Mantel test, using the mantel function in the vegan package [@vegan].

## Construction of D-matrices
Recent studies have found that a small amount of genetic variance could be attributed to dominance in strawberry [@Yamamoto2021; @Feldmann2024; @Sleper2025]. Thus, we also constructed a dominance relationship matrix using the Amatrix function and options dominance = TRUE and ploidy = 2 in AGHmatrix, denoted as dgh.2.